ardupilot_default_airframe: gazebo-iris
ardupilot_dir: ~/ardupilot
global_coordinates:
  altitude: 114.9
  latitude: 61.44997
  longitude: 23.85520
px4_default_airframe: gazebo-classic_iris
px4_dir: ~/PX4-Autopilot
